### PR TITLE
add noEmit to avoid creating js files next to ts files on build

### PR DESCRIPTION
**Pull request by saml-dev**
tiny change :)

### CODE REVIEW

**Comment by saml-dev** [comment]
I will get signed commits set up later today (in 11h)

**Comment by kresnasatya** [comment]
Aha! Now, I understand what's going on if we set `noEmit` to `true`. It will not generate `.js` and `sourcemap` inside `resources/js` directory. But, `noEmit` to `false` default does.

`noEmit` false mode
```
.
└── resources/
    └── js/
        ├── app.js
        ├── app.js.map
        ├── app.ts
        ├── bootstrap.js
        ├── bootstrap.js.map
        ├── bootstrap.ts
        ├── ssr.js
        ├── ssr.js.map
        └── ssr.ts
```

`noEmit` true mode

```diff
.
└── resources/
    └── js/
-        ├── app.js
-        ├── app.js.map
        ├── app.ts
-        ├── bootstrap.js
-        ├── bootstrap.js.map
        ├── bootstrap.ts
-        ├── ssr.js
-        ├── ssr.js.map
        └── ssr.ts
```


By set `noEmit` to `true` also aligns with our friends (React and Vue) in Laravel Breeze.

Vue TS: https://github.com/laravel/breeze/blob/2c7c669326a66112401358282d53550e2ee526d0/stubs/inertia-vue-ts/tsconfig.json#L12

React TS: https://github.com/laravel/breeze/blob/2c7c669326a66112401358282d53550e2ee526d0/stubs/inertia-react-ts/tsconfig.json#L13

**Comment by saml-dev** [comment]
Yes indeed 😁 I believe this was introduced when `tsc` was added to the `build` command in `package.json`

**Comment by saml-dev** [comment]
going to close this and reopen cause I couldn't sign the old commit in the 2 minutes I tried 😂

**Pull request closed without merging**
